### ISSUE TITLE
Some bugs in runtime

### ISSUE THREAD

**Issue by YUZHIGUIYI** [VisualGMQ/toy2d#1]
Dear VisualGMQ, Hello! I recently watched your videos on Bilibili.  I sincerely recommend you to add some settings in CMakeLists.txt, as **sandbox.exe can not find textures or shaders during runtime on Windows platform**, which can be annoying. 
May be you can add some "**CopyDLL**"-like macros in **copydll.cmake** to copy textures and shaders into the path that sandbox.exe exists.
For example,
```cmake
macro(CopyShader target_name)
    add_custom_command(
        TARGET ${target_name} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy ${PROJECT_SOURCE_DIR}/vert.spv $<TARGET_FILE_DIR:${target_name}>)
    add_custom_command(
        TARGET ${target_name} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy ${PROJECT_SOURCE_DIR}/frag.spv $<TARGET_FILE_DIR:${target_name}>)
endmacro(CopyShader)

macro(CopyTexture target_name)
    add_custom_command(
        TARGET ${target_name} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_directory ${PROJECT_SOURCE_DIR}/resources $<TARGET_FILE_DIR:${target_name}>/resources)
endmacro(CopyTexture)
```
and then use them in CMakeLists.txt where **sandbox.cpp** exists.
Thanks!

**Comment by VisualGMQ** [comment]
行，有时间我改改。现在没拷贝的时候可以在根目录运行。你如果愿意也可以直接交一手PR帮我改。

OK, I will fix this in my free time, thank you.Or you can give me a PR.
